In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "mysql+pymysql://root:Yesubabu%408309@localhost/consumer360"
)

In [ ]:
import pymysql
print(pymysql.__version__)

In [4]:
import sys
print(sys.executable)

C:\ProgramData\anaconda3\python.exe

In [5]:
import sys
print(sys.version)

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]

In [6]:
import sys
!{sys.executable} -m pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [1]:
import pymysql
print("PyMySQL installed successfully!")

PyMySQL installed successfully!

In [8]:
query = """
SELECT *
FROM retail_sales_clean
"""

In [9]:
df = pd.read_sql(query, engine)

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,SalesAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom\r,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom\r,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397884 entries, 0 to 397883
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  int64
 7   Country      397884 non-null  object
 8   SalesAmount  397884 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 27.3+ MB

In [13]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
SalesAmount           float64
dtype: object

In [16]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [17]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,SalesAmount
count,397884.000000,397884,397884.000000,397884.000000,397884.000000
mean,12.988238,2011-07-10 23:41:23.511023360,3.116488,15294.423453,22.397000
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000
25%,2.000000,2011-04-07 11:12:00,1.250000,13969.000000,4.680000
50%,6.000000,2011-07-31 14:39:00,1.950000,15159.000000,11.800000
75%,12.000000,2011-10-20 14:33:00,3.750000,16795.000000,19.800000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000
std,179.331775,NaN,22.097877,1713.141560,309.071041

In [18]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
SalesAmount    0
dtype: int64

In [19]:
df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M")

In [20]:
df["InvoiceDay"] = df["InvoiceDate"].dt.date

In [21]:
df["Year"] = df["InvoiceDate"].dt.year

In [22]:
df["Month"] = df["InvoiceDate"].dt.month

In [23]:
df["Week"] = df["InvoiceDate"].dt.isocalendar().week

In [24]:
df["DayName"] = df["InvoiceDate"].dt.day_name()

In [26]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,SalesAmount,InvoiceMonth,InvoiceDay,Year,Month,Week,DayName
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom\r,15.30,2010-12,2010-12-01,2010,12,48,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34,2010-12,2010-12-01,2010,12,48,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom\r,22.00,2010-12,2010-12-01,2010,12,48,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34,2010-12,2010-12-01,2010,12,48,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34,2010-12,2010-12-01,2010,12,48,Wednesday

In [ ]:
df.to_csv(
    "C:\Projects\Consumer360\01_Data\03_Processeddata",
    index=False
)

In [29]:
import os
os.getcwd()

'C:\\Users\\yesub'

In [30]:
df.to_csv(
    r"C:\Projects\Consumer360\01_Data\03_Processeddata\retail_sales_processed.csv",
    index=False,
    encoding="utf-8"
)

In [31]:
print("✅ File saved successfully!")

✅ File saved successfully!