In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
from sqlalchemy import create_engine

In [11]:
engine = create_engine(
    "mysql+pymysql://root:Yesubabu%408309@localhost/consumer360"
)

In [20]:
%pip install lifetimes

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lifetimes in c:\users\yesub\appdata\roaming\python\python313\site-packages (0.11.3)
Requirement already satisfied: numpy>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from lifetimes) (2.3.5)
Requirement already satisfied: scipy>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from lifetimes) (1.16.3)
Requirement already satisfied: pandas>=0.24.0 in c:\programdata\anaconda3\lib\site-packages (from lifetimes) (2.3.3)
Requirement already satisfied: autograd>=1.2.0 in c:\users\yesub\appdata\roaming\python\python313\site-packages (from lifetimes) (1.9.1)
Requirement already satisfied: dill>=0.2.6 in c:\programdata\anaconda3\lib\site-packages (from lifetimes) (0.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.0->lifetimes) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.0->lifetimes) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.0->lifetimes) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->lifetimes) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
from lifetimes import BetaGeoFitter

In [1]:
from lifetimes import GammaGammaFitter

In [2]:
from lifetimes.utils import summary_data_from_transaction_data

In [6]:
query = """
SELECT *
FROM retail_sales_clean
"""

In [12]:
df = pd.read_sql(query, engine)

In [13]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [14]:
clv = summary_data_from_transaction_data(

    df,

    customer_id_col="CustomerID",

    datetime_col="InvoiceDate",

    monetary_value_col="SalesAmount",

    observation_period_end=df["InvoiceDate"].max(),

    freq="D"

)

In [15]:
clv.head()

            frequency  recency      T  monetary_value
CustomerID
12346             0.0      0.0  325.0        0.000000
12347             6.0    365.0  367.0      599.701667
12348             3.0    283.0  358.0      301.480000
12349             0.0      0.0   18.0        0.000000
12350             0.0      0.0  310.0        0.000000

In [16]:
clv.isnull().sum()

frequency         0
recency           0
T                 0
monetary_value    0
dtype: int64

In [17]:
clv = clv[clv["frequency"] > 0]

In [18]:
clv.head()

            frequency  recency      T  monetary_value
CustomerID
12347             6.0    365.0  367.0      599.701667
12348             3.0    283.0  358.0      301.480000
12352             6.0    260.0  296.0      368.256667
12356             2.0    303.0  325.0      269.905000
12358             1.0    149.0  150.0      683.200000

In [22]:
bgf = BetaGeoFitter(penalizer_coef=0.01)

bgf.fit(

    clv["frequency"],

    clv["recency"],

    clv["T"]

)

In [24]:
clv["Predicted_30_Days"] = bgf.predict(

    30,

    clv["frequency"],

    clv["recency"],

    clv["T"]

)

In [25]:
clv.head()

            frequency  recency      T  monetary_value  Predicted_30_Days
CustomerID
12347             6.0    365.0  367.0      599.701667           0.498288
12348             3.0    283.0  358.0      301.480000           0.305898
12352             6.0    260.0  296.0      368.256667           0.589136
12356             2.0    303.0  325.0      269.905000           0.258455
12358             1.0    149.0  150.0      683.200000           0.309731

In [26]:
clv["Predicted_90_Days"] = bgf.predict(

    90,

    clv["frequency"],

    clv["recency"],

    clv["T"]

)

In [27]:
clv.head()

,frequency,recency,T,monetary_value,Predicted_30_Days,Predicted_90_Days
CustomerID,,,,,,
12347,6.0,365.0,367.0,599.701667,0.498288,1.494064
12348,3.0,283.0,358.0,301.480000,0.305898,0.917068
12352,6.0,260.0,296.0,368.256667,0.589136,1.766309
12356,2.0,303.0,325.0,269.905000,0.258455,0.774697
12358,1.0,149.0,150.0,683.200000,0.309731,0.927438

In [28]:
clv["Predicted_365_Days"] = bgf.predict(

    90,

    clv["frequency"],

    clv["recency"],

    clv["T"]

)

In [29]:
clv.head()

,frequency,recency,T,monetary_value,Predicted_30_Days,Predicted_90_Days,Predicted_365_Days
CustomerID,,,,,,,
12347,6.0,365.0,367.0,599.701667,0.498288,1.494064,1.494064
12348,3.0,283.0,358.0,301.480000,0.305898,0.917068,0.917068
12352,6.0,260.0,296.0,368.256667,0.589136,1.766309,1.766309
12356,2.0,303.0,325.0,269.905000,0.258455,0.774697,0.774697
12358,1.0,149.0,150.0,683.200000,0.309731,0.927438,0.927438

In [30]:
ggf = GammaGammaFitter(penalizer_coef=0.01)

ggf.fit(

    clv["frequency"],

    clv["monetary_value"]

)

In [31]:
clv["Expected_Avg_Sales"] = ggf.conditional_expected_average_profit(

    clv["frequency"],

    clv["monetary_value"]

)

In [32]:
clv.head()

,frequency,recency,T,monetary_value,Predicted_30_Days,Predicted_90_Days,Predicted_365_Days,Expected_Avg_Sales
CustomerID,,,,,,,,
12347,6.0,365.0,367.0,599.701667,0.498288,1.494064,1.494064,618.580281
12348,3.0,283.0,358.0,301.480000,0.305898,0.917068,0.917068,321.698923
12352,6.0,260.0,296.0,368.256667,0.589136,1.766309,1.766309,380.090885
12356,2.0,303.0,325.0,269.905000,0.258455,0.774697,0.774697,298.146326
12358,1.0,149.0,150.0,683.200000,0.309731,0.927438,0.927438,834.789440

In [33]:
clv["CLV"] = ggf.customer_lifetime_value(

    bgf,

    clv["frequency"],

    clv["recency"],

    clv["T"],

    clv["monetary_value"],

    time=12,

    freq="D",

    discount_rate=0.01

)

In [34]:
clv.head()

,frequency,recency,T,monetary_value,Predicted_30_Days,Predicted_90_Days,Predicted_365_Days,Expected_Avg_Sales,CLV
CustomerID,,,,,,,,,
12347,6.0,365.0,367.0,599.701667,0.498288,1.494064,1.494064,618.580281,3460.873746
12348,3.0,283.0,358.0,301.480000,0.305898,0.917068,0.917068,321.698923,1104.315389
12352,6.0,260.0,296.0,368.256667,0.589136,1.766309,1.766309,380.090885,2513.460729
12356,2.0,303.0,325.0,269.905000,0.258455,0.774697,0.774697,298.146326,864.157532
12358,1.0,149.0,150.0,683.200000,0.309731,0.927438,0.927438,834.789440,2890.453636

In [36]:
top_clv = clv.sort_values(

    by="CLV",

    ascending=False

)

top_clv.head(10)

,frequency,recency,T,monetary_value,Predicted_30_Days,Predicted_90_Days,Predicted_365_Days,Expected_Avg_Sales,CLV
CustomerID,,,,,,,,,
16446,1.0,205.0,205.0,168469.600000,0.252145,0.755212,0.755212,204762.328199,577587.931847
14646,44.0,353.0,354.0,6366.705909,3.080607,9.237900,9.237900,6392.536896,221213.225199
18102,25.0,367.0,367.0,9349.477200,1.745740,5.234978,5.234978,9416.375779,184653.566112
17450,26.0,359.0,367.0,7404.690385,1.811093,5.430960,5.430960,7455.650932,151678.155523
14096,16.0,97.0,101.0,4071.434375,2.762696,8.280162,8.280162,4117.267368,127533.538137
14911,131.0,372.0,373.0,1093.661679,8.591257,25.763594,25.763594,1095.171112,105704.021111
12415,15.0,313.0,337.0,7860.210000,1.164916,3.493069,3.493069,7954.434760,104066.019698
14156,42.0,362.0,371.0,2787.081667,2.836291,8.505378,8.505378,2798.979137,89181.627776
17511,27.0,371.0,373.0,3305.060741,1.852650,5.555612,5.555612,3327.034017,69240.182539
16029,38.0,335.0,373.0,2034.808421,2.552631,7.654745,7.654745,2044.439213,58625.464864

In [37]:
clv["CLV"].describe()

count      2790.000000
mean       3096.526619
std       13759.642258
min          12.743805
25%         788.951117
50%        1520.559475
75%        2848.237995
max      577587.931847
Name: CLV, dtype: float64

In [41]:
clv.to_csv(
    r"C:\Projects\Consumer360\01_Data\04_Output\Customer_CLV.csv",
    index=False,
    encoding="utf-8"
)

In [42]:
clv.to_sql(

    "customer_clv",

    engine,

    if_exists="replace"

)

2790

In [40]:
clv.sort_values(

    "CLV",

    ascending=False

)[

["CLV",

"Predicted_365_Days",

"Expected_Avg_Sales"]

].head(10)

                      CLV  Predicted_365_Days  Expected_Avg_Sales
CustomerID
16446       577587.931847            0.755212       204762.328199
14646       221213.225199            9.237900         6392.536896
18102       184653.566112            5.234978         9416.375779
17450       151678.155523            5.430960         7455.650932
14096       127533.538137            8.280162         4117.267368
14911       105704.021111           25.763594         1095.171112
12415       104066.019698            3.493069         7954.434760
14156        89181.627776            8.505378         2798.979137
17511        69240.182539            5.555612         3327.034017
16029        58625.464864            7.654745         2044.439213

In [44]:
clv.head()

,frequency,recency,T,monetary_value,Predicted_30_Days,Predicted_90_Days,Predicted_365_Days,Expected_Avg_Sales,CLV
CustomerID,,,,,,,,,
12347,6.0,365.0,367.0,599.701667,0.498288,1.494064,1.494064,618.580281,3460.873746
12348,3.0,283.0,358.0,301.480000,0.305898,0.917068,0.917068,321.698923,1104.315389
12352,6.0,260.0,296.0,368.256667,0.589136,1.766309,1.766309,380.090885,2513.460729
12356,2.0,303.0,325.0,269.905000,0.258455,0.774697,0.774697,298.146326,864.157532
12358,1.0,149.0,150.0,683.200000,0.309731,0.927438,0.927438,834.789440,2890.453636