In [9]:
import pandas as pd
from sqlalchemy import create_engine

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [10]:
engine = create_engine(
    "mysql+pymysql://root:Yesubabu%408309@localhost/consumer360"
)

In [11]:
query = """
SELECT
    InvoiceNo,
    Description,
    Quantity
FROM retail_sales_clean
WHERE
    Quantity > 0
    AND Description IS NOT NULL;
"""

df = pd.read_sql(query, engine)

In [12]:
df.head()

  InvoiceNo                          Description  Quantity
0    536365   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365                  WHITE METAL LANTERN         6
2    536365       CREAM CUPID HEARTS COAT HANGER         8
3    536365  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365       RED WOOLLY HOTTIE WHITE HEART.         6

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 397884 entries, 0 to 397883
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  str
 1   Description  397884 non-null  str
 2   Quantity     397884 non-null  int64
dtypes: int64(1), str(2)
memory usage: 9.1 MB

In [14]:
df.isnull().sum()

InvoiceNo      0
Description    0
Quantity       0
dtype: int64

In [15]:
basket = (
    df.groupby(
        ["InvoiceNo", "Description"]
    )["Quantity"]
    .sum()
    .unstack(fill_value=0)
)

In [16]:
basket.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
basket = basket.gt(0)

In [18]:
basket.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536366,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536367,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536368,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536369,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
product_counts = basket.sum(axis=0)

basket = basket.loc[:, product_counts >= 10]

In [20]:
basket.shape

(18532, 2941)

In [21]:
frequent_items = apriori(
    basket,
    min_support=0.02,
    use_colnames=True
)

In [22]:
frequent_items.head()

    support                                      itemsets
0  0.021692         frozenset({3 STRIPEY MICE FELTCRAFT})
1  0.039175           frozenset({6 RIBBONS RUSTIC CHARM})
2  0.025146  frozenset({60 CAKE CASES VINTAGE CHRISTMAS})
3  0.035452      frozenset({60 TEATIME FAIRY CAKE CASES})
4  0.027034   frozenset({72 SWEETHEART FAIRY CAKE CASES})

In [23]:
frequent_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   support   243 non-null    float64
 1   itemsets  243 non-null    object
dtypes: float64(1), object(1)
memory usage: 3.9+ KB

In [24]:
rules = association_rules(
    frequent_items,
    metric="lift",
    min_threshold=1,
    num_itemsets=len(frequent_items)
)

In [25]:
rules = association_rules(
    frequent_items,
    metric="lift",
    min_threshold=1
)

In [27]:
top_rules = rules.sort_values(
    by="lift",
    ascending=False
)

In [28]:
top_rules.head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
73,frozenset({PINK REGENCY TEACUP AND SAUCER}),"frozenset({GREEN REGENCY TEACUP AND SAUCER, RO...",0.030002,0.029193,0.021045,0.701439,24.027846,1.0,0.020169,3.251619,0.988024,0.551627,0.692461,0.711163
72,"frozenset({GREEN REGENCY TEACUP AND SAUCER, RO...",frozenset({PINK REGENCY TEACUP AND SAUCER}),0.029193,0.030002,0.021045,0.720887,24.027846,1.0,0.020169,3.475290,0.987201,0.551627,0.712254,0.711163
71,"frozenset({PINK REGENCY TEACUP AND SAUCER, ROS...",frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.023527,0.037287,0.021045,0.894495,23.989564,1.0,0.020167,9.124846,0.981405,0.529172,0.890409,0.729447
74,frozenset({GREEN REGENCY TEACUP AND SAUCER}),"frozenset({PINK REGENCY TEACUP AND SAUCER, ROS...",0.037287,0.023527,0.021045,0.564399,23.989564,1.0,0.020167,2.241671,0.995432,0.529172,0.553904,0.729447
8,frozenset({PINK REGENCY TEACUP AND SAUCER}),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.030002,0.037287,0.024822,0.827338,22.188466,1.0,0.023703,5.575714,0.984468,0.584498,0.820651,0.746520
9,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({PINK REGENCY TEACUP AND SAUCER}),0.037287,0.030002,0.024822,0.665702,22.188466,1.0,0.023703,2.901595,0.991917,0.584498,0.655362,0.746520
70,"frozenset({PINK REGENCY TEACUP AND SAUCER, GRE...",frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.024822,0.042251,0.021045,0.847826,20.066300,1.0,0.019996,6.293778,0.974350,0.457210,0.841113,0.672955
75,frozenset({ROSES REGENCY TEACUP AND SAUCER }),"frozenset({PINK REGENCY TEACUP AND SAUCER, GRE...",0.042251,0.024822,0.021045,0.498084,20.066300,1.0,0.019996,1.942912,0.992082,0.457210,0.485309,0.672955
62,frozenset({PINK REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.030002,0.042251,0.023527,0.784173,18.559754,1.0,0.022259,4.437569,0.975384,0.482835,0.774651,0.670503
63,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({PINK REGENCY TEACUP AND SAUCER}),0.042251,0.030002,0.023527,0.556833,18.559754,1.0,0.022259,2.188785,0.987858,0.482835,0.543125,0.670503
13,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.042251,0.037287,0.029193,0.690932,18.530185,1.0,0.027617,3.114894,0.987768,0.579850,0.678962,0.736928
12,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.037287,0.042251,0.029193,0.782923,18.530185,1.0,0.027617,4.412029,0.982675,0.579850,0.773347,0.736928
4,frozenset({DOLLY GIRL LUNCH BOX}),frozenset({SPACEBOY LUNCH BOX }),0.033240,0.037988,0.022879,0.688312,18.119023,1.0,0.021617,3.086454,0.977294,0.473214,0.676004,0.645292
5,frozenset({SPACEBOY LUNCH BOX }),frozenset({DOLLY GIRL LUNCH BOX}),0.037988,0.033240,0.022879,0.602273,18.119023,1.0,0.021617,2.430711,0.982118,0.473214,0.588598,0.645292
6,frozenset({GARDENERS KNEELING PAD CUP OF TEA }),frozenset({GARDENERS KNEELING PAD KEEP CALM }),0.034265,0.040794,0.024984,0.729134,17.873424,1.0,0.023586,3.541254,0.977547,0.498922,0.717614,0.670784
7,frozenset({GARDENERS KNEELING PAD KEEP CALM }),frozenset({GARDENERS KNEELING PAD CUP OF TEA }),0.040794,0.034265,0.024984,0.612434,17.873424,1.0,0.023586,2.491794,0.984201,0.498922,0.598683,0.670784
1,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.047324,0.042575,0.028599,0.604333,14.194548,1.0,0.026584,2.419774,0.975725,0.466549,0.586738,0.638035
0,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE RED }),0.042575,0.047324,0.028599,0.671736,14.194548,1.0,0.026584,2.902169,0.970886,0.466549,0.655430,0.638035
2,frozenset({ALARM CLOCK BAKELIKE PINK}),frozenset({ALARM CLOCK BAKELIKE RED }),0.033078,0.047324,0.021368,0.646003,13.650778,1.0,0.019803,2.691201,0.958448,0.361974,0.628419,0.548771
3,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE PINK}),0.047324,0.033078,0.021368,0.451539,13.650778,1.0,0.019803,1.762974,0.972779,0.361974,0.432777,0.548771

In [29]:
bottom_rules = rules.sort_values(
    by="lift",
    ascending=True
)

In [30]:
bottom_rules.head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
25,frozenset({LUNCH BAG RED RETROSPOT}),frozenset({JUMBO BAG RED RETROSPOT}),0.069501,0.086337,0.022933,0.329969,3.821865,1.0,0.016933,1.363613,0.793497,0.172554,0.266654,0.297797
24,frozenset({JUMBO BAG RED RETROSPOT}),frozenset({LUNCH BAG RED RETROSPOT}),0.086337,0.069501,0.022933,0.265625,3.821865,1.0,0.016933,1.267062,0.808118,0.172554,0.210773,0.297797
60,frozenset({SPOTTY BUNTING}),frozenset({PARTY BUNTING}),0.054123,0.074412,0.020991,0.387836,5.212027,1.0,0.016963,1.511995,0.854377,0.195183,0.338622,0.334962
61,frozenset({PARTY BUNTING}),frozenset({SPOTTY BUNTING}),0.074412,0.054123,0.020991,0.282088,5.212027,1.0,0.016963,1.317540,0.873105,0.195183,0.241010,0.334962
20,frozenset({JUMBO BAG RED RETROSPOT}),frozenset({JUMBO SHOPPER VINTAGE RED PAISLEY}),0.086337,0.042629,0.021368,0.247500,5.805911,1.0,0.017688,1.272254,0.905982,0.198596,0.213993,0.374383
21,frozenset({JUMBO SHOPPER VINTAGE RED PAISLEY}),frozenset({JUMBO BAG RED RETROSPOT}),0.042629,0.086337,0.021368,0.501266,5.805911,1.0,0.017688,1.831964,0.864620,0.198596,0.454138,0.374383
66,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({REGENCY CAKESTAND 3 TIER}),0.042251,0.091895,0.022664,0.536398,5.837074,1.0,0.018781,1.958805,0.865239,0.203291,0.489485,0.391511
67,frozenset({REGENCY CAKESTAND 3 TIER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.091895,0.042251,0.022664,0.246624,5.837074,1.0,0.018781,1.271275,0.912539,0.203291,0.213388,0.391511
11,frozenset({REGENCY CAKESTAND 3 TIER}),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.091895,0.037287,0.020181,0.219612,5.889809,1.0,0.016755,1.233635,0.914228,0.185149,0.189387,0.380429
10,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({REGENCY CAKESTAND 3 TIER}),0.037287,0.091895,0.020181,0.541245,5.889809,1.0,0.016755,1.979497,0.862370,0.185149,0.494821,0.380429
64,frozenset({RED HANGING HEART T-LIGHT HOLDER}),frozenset({WHITE HANGING HEART T-LIGHT HOLDER}),0.036639,0.106357,0.024552,0.670103,6.300533,1.0,0.020655,2.708857,0.873280,0.207289,0.630841,0.450475
65,frozenset({WHITE HANGING HEART T-LIGHT HOLDER}),frozenset({RED HANGING HEART T-LIGHT HOLDER}),0.106357,0.036639,0.024552,0.230847,6.300533,1.0,0.020655,1.252496,0.941408,0.207289,0.201594,0.450475
36,frozenset({LUNCH BAG APPLE DESIGN}),frozenset({LUNCH BAG RED RETROSPOT}),0.046730,0.069501,0.020991,0.449192,6.463059,1.0,0.017743,1.689333,0.886710,0.220397,0.408050,0.375605
37,frozenset({LUNCH BAG RED RETROSPOT}),frozenset({LUNCH BAG APPLE DESIGN}),0.069501,0.046730,0.020991,0.302019,6.463059,1.0,0.017743,1.365753,0.908410,0.220397,0.267803,0.375605
22,frozenset({JUMBO STORAGE BAG SUKI}),frozenset({JUMBO BAG RED RETROSPOT}),0.041766,0.086337,0.023419,0.560724,6.494580,1.0,0.019813,2.079927,0.882900,0.223711,0.519214,0.415987
23,frozenset({JUMBO BAG RED RETROSPOT}),frozenset({JUMBO STORAGE BAG SUKI}),0.086337,0.041766,0.023419,0.271250,6.494580,1.0,0.019813,1.314901,0.925971,0.223711,0.239487,0.415987
48,frozenset({LUNCH BAG SPACEBOY DESIGN }),frozenset({LUNCH BAG RED RETROSPOT}),0.053313,0.069501,0.025200,0.472672,6.800900,1.0,0.021494,1.764554,0.900996,0.258154,0.433285,0.417625
49,frozenset({LUNCH BAG RED RETROSPOT}),frozenset({LUNCH BAG SPACEBOY DESIGN }),0.069501,0.053313,0.025200,0.362578,6.800900,1.0,0.021494,1.485180,0.916671,0.258154,0.326681,0.417625
40,frozenset({LUNCH BAG CARS BLUE}),frozenset({LUNCH BAG RED RETROSPOT}),0.052126,0.069501,0.024714,0.474120,6.821734,1.0,0.021091,1.769413,0.900341,0.255011,0.434841,0.414855
41,frozenset({LUNCH BAG RED RETROSPOT}),frozenset({LUNCH BAG CARS BLUE}),0.069501,0.052126,0.024714,0.355590,6.821734,1.0,0.021091,1.470918,0.917153,0.255011,0.320152,0.414855

In [31]:
rules.sort_values(
    by="confidence",
    ascending=False
)[
    [
        "antecedents",
        "consequents",
        "confidence",
        "lift"
    ]
].head(10)

,antecedents,consequents,confidence,lift
71,"frozenset({PINK REGENCY TEACUP AND SAUCER, ROS...",frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.894495,23.989564
70,"frozenset({PINK REGENCY TEACUP AND SAUCER, GRE...",frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.847826,20.066300
8,frozenset({PINK REGENCY TEACUP AND SAUCER}),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.827338,22.188466
62,frozenset({PINK REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.784173,18.559754
12,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.782923,18.530185
6,frozenset({GARDENERS KNEELING PAD CUP OF TEA }),frozenset({GARDENERS KNEELING PAD KEEP CALM }),0.729134,17.873424
72,"frozenset({GREEN REGENCY TEACUP AND SAUCER, RO...",frozenset({PINK REGENCY TEACUP AND SAUCER}),0.720887,24.027846
73,frozenset({PINK REGENCY TEACUP AND SAUCER}),"frozenset({GREEN REGENCY TEACUP AND SAUCER, RO...",0.701439,24.027846
13,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.690932,18.530185
4,frozenset({DOLLY GIRL LUNCH BOX}),frozenset({SPACEBOY LUNCH BOX }),0.688312,18.119023

In [32]:
rules.sort_values(
    by="support",
    ascending=False
)[
    [
        "antecedents",
        "consequents",
        "support",
        "lift"
    ]
].head(10)

,antecedents,consequents,support,lift
16,frozenset({JUMBO BAG PINK POLKADOT}),frozenset({JUMBO BAG RED RETROSPOT}),0.029463,7.260672
17,frozenset({JUMBO BAG RED RETROSPOT}),frozenset({JUMBO BAG PINK POLKADOT}),0.029463,7.260672
13,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.029193,18.530185
12,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.029193,18.530185
0,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE RED }),0.028599,14.194548
1,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.028599,14.194548
47,frozenset({LUNCH BAG RED RETROSPOT}),frozenset({LUNCH BAG PINK POLKADOT}),0.028221,8.082737
46,frozenset({LUNCH BAG PINK POLKADOT}),frozenset({LUNCH BAG RED RETROSPOT}),0.028221,8.082737
31,frozenset({LUNCH BAG RED RETROSPOT}),frozenset({LUNCH BAG BLACK SKULL.}),0.027898,7.071006
30,frozenset({LUNCH BAG BLACK SKULL.}),frozenset({LUNCH BAG RED RETROSPOT}),0.027898,7.071006

In [33]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE RED }),0.042575,0.047324,0.028599,0.671736,14.194548,1.0,0.026584,2.902169,0.970886,0.466549,0.655430,0.638035
1,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.047324,0.042575,0.028599,0.604333,14.194548,1.0,0.026584,2.419774,0.975725,0.466549,0.586738,0.638035
2,frozenset({ALARM CLOCK BAKELIKE PINK}),frozenset({ALARM CLOCK BAKELIKE RED }),0.033078,0.047324,0.021368,0.646003,13.650778,1.0,0.019803,2.691201,0.958448,0.361974,0.628419,0.548771
3,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE PINK}),0.047324,0.033078,0.021368,0.451539,13.650778,1.0,0.019803,1.762974,0.972779,0.361974,0.432777,0.548771
4,frozenset({DOLLY GIRL LUNCH BOX}),frozenset({SPACEBOY LUNCH BOX }),0.033240,0.037988,0.022879,0.688312,18.119023,1.0,0.021617,3.086454,0.977294,0.473214,0.676004,0.645292

In [34]:
print("Total Rules :", len(rules))

Total Rules : 76

In [35]:
rules = rules.sort_values(
    by="lift",
    ascending=False
)

In [36]:
rules.to_csv(
    r"C:\Projects\Consumer360\01_Data\04_Output\Market_Basket_rules.csv",
    index=False,
    encoding="utf-8"
)

In [41]:
rules["antecedents"] = rules["antecedents"].apply(
    lambda x: ", ".join(list(x))
)

rules["consequents"] = rules["consequents"].apply(
    lambda x: ", ".join(list(x))
)

In [42]:
rules.to_sql(
    name="market_basket_rules",
    con=engine,
    if_exists="replace",
    index=False
)

76

In [43]:
print("Table Saved Successfully")

Table Saved Successfully

In [44]:
print(rules.dtypes)

antecedents               str
consequents               str
antecedent support    float64
consequent support    float64
support               float64
confidence            float64
lift                  float64
representativity      float64
leverage              float64
conviction            float64
zhangs_metric         float64
jaccard               float64
certainty             float64
kulczynski            float64
dtype: object